site_name: Seafile Admin Manual
site_author: seafile
docs_dir: ./manual
site_url: https://haiwen.github.io/seafile-admin-docs/

repo_name: haiwen/seafile-admin-docs
repo_url: https://github.com/haiwen/seafile-admin-docs/
edit_uri: blob/master/manual

copyright: Copyright &copy; 2024 Seafile Ltd.

theme:
  name: material
  logo: media/seafile-transparent-1024.png
  favicon: media/favicon.ico
  features:
    - navigation.footer
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - awesome-pages
  - mike

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/haiwen/seafile-admin-docs/
  version:
    provider: mike
  status:
    new: Work in progress

extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
      toc_depth: "1-4"
  - pymdownx.superfences: # allows 1) nesting of fences 2) custom fences 3) disable indented code
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed: # provides a syntax to easily add tabbed Markdown content
      alternate_style: true

# Page tree
nav:
  - Introduction:
    - Introduction: README.md
    - Seafile Components: introduction/components.md
    - File permission management: introduction/file_permission_management.md
    - License: introduction/seafile_professional_sdition_software_license_agreement.md
    - Roadmap: introduction/roadmap.md
    - Contribution: introduction/contribution.md
  - Setup:
    - Overview: setup/overview.md
    - Single node installation: setup/single_node_installation.md
    - HTTPS and Caddy: setup/caddy.md
    - Advanced topics:
      - Storage Backends:
        - S3 Backend: setup/setup_with_amazon_s3.md
        - Ceph Backend: setup/setup_with_ceph.md
        - OpenStack Swift Backend: setup/setup_with_swift.md
        - Alibaba OSS: setup/setup_with_oss.md
        - Multiple Storage Backends: setup/setup_with_multiple_storage_backends.md
        - Data migration: setup/migrate_backends_data.md
      - Seafile Docker autostart: setup/seafile_docker_autostart.md
      - Deploy with an existing MySQL server: setup/setup_with_an_existing_mysql_server.md
      - Run Seafile as non root user inside docker: setup/run_seafile_as_non_root_user_inside_docker.md
    - Cluster installation:
      - Seafile Docker Cluster Deployment: setup/cluster_deploy_with_docker.md
      - Setup with Kubernetes (K8s): setup/cluster_deploy_with_k8s.md
    - Migration:
      - Migration from Seafile Community: setup/migrate_ce_to_pro_with_docker.md
      - Migrate from non-docker deployment: setup/migrate_non_docker_to_docker.md
  - Setup (binary):
    - Outline: setup_binary/outline.md
    - Single node installation: setup_binary/installation_by_binary.md
    - HTTPS with Nginx: setup_binary/https_with_nginx.md
    - HTTPS with Apache: setup_binary/https_with_apache.md
    - Cluster deployment:
      - Deploy in a cluster: setup_binary/deploy_in_a_cluster.md
      - Search and background tasks in a cluster: setup_binary/enable_search_and_background_tasks_in_a_cluster.md
      - Memcache and MariaDB Cluster: setup_binary/memcached_mariadb_cluster.md
      - Setup Seafile cluster with NFS: setup_binary/setup_seafile_cluster_with_nfs.md
    - Other deployment notes:
      - Start Seafile at System Bootup: setup_binary/start_seafile_at_system_bootup.md
      - Logrotate: setup_binary/using_logrotate.md
      - Config fail2ban: setup_binary/fail2ban.md
      - Migrate From SQLite to MySQL: setup_binary/migrate_from_sqlite_to_mysql.md
  - Extensions:
    - Extra Seafile components:
      - SeaDoc Integration: extension/setup_seadoc.md
      - Notification Server: extension/notification-server.md
      - WebDAV extension: extension/webdav.md
      - FUSE extension: extension/fuse.md
    - Online Office:
      - Collabora Online Integration: extension/libreoffice_online.md
      - OnlyOffice Integration: extension/only_office.md
      - Office Online Server Integration (Pro): extension/office_web_app.md
    - Virus Scan (Pro):
      - Outline: extension/virus_scan.md
      - Virus scan with ClamAV: extension/virus_scan_with_clamav.md
      - Virus scan with Kav4fs: extension/virus_scan_with_kav4fs.md
  - Configuration:
    - Authentication & Users:
      - LDAP/AD Integration: config/ldap.md
      - Single Sign On:
        - Outline: config/single_sign_on.md
        - OAuth Authentication: config/oauth.md
        - Remote User Authentication: config/remote_user.md
        - Shibboleth Authentication: config/shibboleth_authentication.md
        - Auto Login to SeaDrive on Windows: config/auto_login_seadrive.md
        - SAML 2.0 (Pro): config/saml2_in_10.0.md
        - Switch authentication: config/auth_switch.md
      - Advanced User Management (Pro):
        - Multi-Institutions Support: config/multi_institutions.md
        - Roles and Permissions: config/roles_permissions.md
        - Administrator Roles and Permissions: config/admin_roles_permissions.md
        - Multi-Tenancy Support: config/multi_tenancy.md
    - Advanced File Search configuration (Pro): config/details_about_file_search.md
    - Open Cloud Mesh: config/ocm.md
    - Available configuration options:
      - Outline: config/README.md
      - Environment variables: config/env.md
      - ccnet.conf: config/ccnet-conf.md
      - seafile.conf: config/seafile-conf.md
      - seahub_settings.py: config/seahub_settings_py.md
      - seafevents.conf: config/seafevents-conf.md
      - Seahub customization: config/seahub_customization.md
      - Email Sending: config/sending_email.md
  - Administration:
    - Outline: administration/README.md
    - Account management: administration/account.md
    - Two-factor Authentication: administration/two_factor_authentication.md
    - Security features: administration/security_features.md
    - Access logs and auditing: administration/auditing.md
    - Export report: administration/export_report.md
    - Logs: administration/logs.md
    - Backup and Recovery: administration/backup_recovery.md
    - Seafile FSCK: administration/seafile_fsck.md
    - Seafile GC: administration/seafile_gc.md
    - Clean database: administration/clean_database.md
  - Upgrade:
    - Outline: upgrade/upgrade.md
    - Upgrade Seafile Docker: upgrade/upgrade_docker.md
    - Upgrade Seafile Cluster: upgrade/upgrade_a_cluster.md
    - Upgrade Seafile Cluster (Docker): upgrade/upgrade_a_cluster_docker.md
    - Upgrade notes for 7.0.x: upgrade/upgrade_notes_for_7.0.x.md
    - Upgrade notes for 7.1.x: upgrade/upgrade_notes_for_7.1.x.md
    - Upgrade notes for 8.0.x: upgrade/upgrade_notes_for_8.0.x.md
    - Upgrade notes for 9.0.x: upgrade/upgrade_notes_for_9.0.x.md
    - Upgrade notes for 10.0.x: upgrade/upgrade_notes_for_10.0.x.md
    - Upgrade notes for 11.0.x: upgrade/upgrade_notes_for_11.0.x.md
    - Upgrade notes for 12.0.x: upgrade/upgrade_notes_for_12.0.x.md
  - Developing:
    - Outline: develop/README.md
    - How to Build Seafile:
      - Outline: develop/build_seafile.md
      - Linux: develop/linux.md
      - macOS: develop/osx.md
      - Windows: develop/windows.md
      - Server development: develop/server.md
      - Server binary package: develop/rpi.md
    - Translation: develop/translation.md
    - Web API V2.1: develop/web_api_v2.1.md
    - PHP API: https://github.com/rene-s/Seafile-PHP-SDK
    - Data Model: develop/data_model.md
  - ChangeLog:
    - Seafile Community Edition: changelog/server-changelog.md
    - Seafile Professional Edition: changelog/changelog-for-seafile-professional-server.md
    - Seafile Client: changelog/client-changelog.md
    - Drive Client: changelog/drive-client-changelog.md
